language: python

dist: xenial

matrix:
  include:
    - python: '3.6'
      env: ORANGE="release"  RUN_PYLINT=true

    - python: '3.6'
      env: ORANGE="3.11.0"

    - python: '3.6'
      env: ORANGE="release"  UPLOAD_COVERAGE=true

    - python: '3.6'
      env: ORANGE="master"

cache:
    apt: true
    pip: true
    directories:
        - $TRAVIS_BUILD_DIR/pyqt

install:
    # Update pip to be able to install wheel dependencies
    - pip install -U pip wheel codecov
    # 20180124 force PyQt 5.9.2 due to segfaults on new 5.10
    - pip install sip pyqt5==5.9.2
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    # opusFC is not installed by default - install for tests
    - pip install opusFC
    - pip install -e .

script:
    - source $TRAVIS_BUILD_DIR/.travis/stage_script.sh
