language: python

sudo: false

matrix:
  include:
    - python: '3.4'
      env: PYQT4=true ORANGE="3.4.4"

    - python: '3.5'
      env: PYQT5=true ORANGE="3.4.4"

    - python: '3.5'
      env: PYQT5=true ORANGE="release"

    - python: '3.5'
      env: PYQT5=true ORANGE="master"

cache:
    apt: true
    pip: true
    directories:
        - $TRAVIS_BUILD_DIR/pyqt

install:
    # Update pip to be able to install wheel dependencies
    - pip install -U pip wheel
    - source $TRAVIS_BUILD_DIR/.travis/install_pyqt.sh
    - source $TRAVIS_BUILD_DIR/.travis/install_orange.sh
    - pip install -e .

before_script:  # required for widget tests
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script: python setup.py test
